### ISSUE TITLE
passive ftp access

### ISSUE THREAD

**Issue by deepend-tildeclub** [scottadkin/Node-UTStats-ftp#7]
Is it possible to connect to a ftp passively? 

Thanks

**Comment by scottadkin** [comment]
I don't think it's possible with the ftp package I used to do that.
https://www.npmjs.com/package/ftp

**Comment by deepend-tildeclub** [comment]
Looks like maybe since it does mention "pasvTimeout" at that URL you posted.  in the end I moved my UT server to a separate IP instead of having it behind a NAT.   No problems.  Might of even been an issue with my configuration instead of the passive ability being the problem.   Thanks for your reply.

Great job on the stats site.  Works and looks great.
