### ISSUE TITLE
Accessed none warnings

### ISSUE THREAD

**Issue by deltabatonix** [scottadkin/Node-UTStats-ftp#8]
Just started using NodeStats and noticed loads of warnings in the log, as per below (on every map change)

ut-server-pug_1  | ??????????????? NodeUTStats started ???????????????
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'
ut-server-pug_1  | NodeUTStatsMutator DM-Deck16][.NodeUTStatsMutator0 (Function NodeUTStats.NodeUTStatsMutator.printLog:0018) Accessed None 'LocalLog'

**Comment by scottadkin** [comment]
What game version is the server running?

You have installed the original UTStats first, because node utstats adds stuff to the utstats log.

**Comment by deltabatonix** [comment]
It's a linux machine running 469b (release build). Are you on discord?

**Comment by scottadkin** [comment]
Yeah I'm Ooper#4172
